### ISSUE TITLE
'Received unexpected chunk upload response' when uploading a video

### ISSUE THREAD

**Issue by gu-ma** [ping/instagram_private_api#104]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

I got an error when trying to upload a video using `api.post_video` I've tried with and without encoding, also tried to encode the thumb, size and duration without `media.prepare_video` but nothing seem to work. When I save the video and upload it to IG with the app, as suggested [here](https://github.com/ping/instagram_private_api/issues/9) , it works just fine...

---

Python 3.6.4 :: Anaconda, Inc.

Code:

```python
...
data, size, duration, thumb = media.prepare_video(filepath, aspect_ratios=MediaRatios.standard, skip_reencoding=True, save_path='video.mp4')
api.post_video(data, size, duration, thumb)
...
```

Error/Debug Log:

```python
WARNING:py.warnings:/Users/guillaume/miniconda3/envs/tf/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py:132: UserWarning: Warning: in file /var/folders/7s/5vyv23b511g2vc2zcvtdc1z40000gn/T/ipae_drkku0o2.mp4, 1536000 bytes wanted but 0 bytes read,at frame 395/396, at time 13.17/13.17 sec. Using the last valid frame instead.
  UserWarning)

WARNING:py.warnings:/Users/guillaume/miniconda3/envs/tf/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py:497: UserWarning: This endpoint has not been fully tested.
  warnings.warn('This endpoint has not been fully tested.', UserWarning)

DEBUG:instagram_private_api.client:REQUEST: https://i.instagram.com/api/v1/upload/video/ POST
DEBUG:instagram_private_api.client:DATA: b'_csrftoken=Lnzv89pHahkVWR3uBzf6GEasInm6CaNV&_uuid=80a0f3f4-ae91-11e8-9886-985aeb8e7954&upload_id=1536176631309&media_type=2&upload_media_duration_ms=13170&upload_media_width=612&upload_media_height=816'
DEBUG:instagram_private_api.client:RESPONSE: 200 {"video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn\u0026vx_token=2\u0026staging_in_tao=0", "job": "AQC6x9LvN1YG-oNHY3v51K5HX9BMft3lRp3nmwGj5RuY06sK4xQnbEmVua_aG0jYUxHa433-Lpv1IHWbZjrnwif43l3qPuEUJIcKwTMcoKUMNtpJTEu2xAEEqWHPqHxLdafKle7TiHOGWszaiVK37YEMq1B4VKNhNDYCfc_ZhQYYtTTq_xFCTxz7SMDZhLGgZ2agpRpEghqUERuWrxiW9aFaCBfhP1JUAn6XSD1dCm_lQqOMDaTWD53XL8ZynBaNEZwi_MriS8xSEhVRarxjPg-MqDYrK50EZadGxLveAZuPqF_fiQXm_ayRxQ3R7rlQgzen8BA_UWu3RUjNU-kqg4VuMegXQDuu6ljxRwhEyMdmdg", "expires": 1851536632.2875023}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn\u0026vx_token=1\u0026staging_in_tao=0", "job": "AQDvmA78eBVFus9uCTZzf_fxCqaJbXcpg9ouDsHb02RmkYA5pZ3FCp4zDBjWLaPa2Ggh1HXuZ0hNIJeF8QWIdnC0zV6uWNB_jlliKvR7y0CWf9YOvEkUDEAyCwhx8J7KVq7Mchf4jNzpQW7UioNAA3TXlO0yw2wlxqjrTkAvX-wky07i0em8jnMAwdVFWSviV38q3Rkp1Ijbg-MMhmROZ5H3PGUvhPIfV-6ZdRksGoTPl87JgAqNFsV6EwHDj4zZUYv6bLOxpQ84RapsBVauP9O3OKaJt4qM5s3R75XjFLxAG48sf2mEuEjJHVdJwa7wHxbPLlDe46d9YGuAT7e4uKZrhc1uw0RyG4OnQkx0jSE5HQ", "expires": 1851536632.2877524}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn\u0026vx_token=4\u0026staging_in_tao=0", "job": "AQDK5HXX1qnINlwrLpdh5hiKoNbQLvjbhlJI8b2CuLw9MsZkxO6idOrzud9oVxF4uIAuaw4tf0X1rm25dyuJM4TeAeh4qCk0MhdIkhWHcESdODhRJBWIHGEyTKYB64RsDBqQTef2WTtPfjkbXKCg_giC1zCH58qQWw0iJxY-m-jlGfmZJ1kgr7hTTMikFcqQ6E8YqraViJ2SYKs1zuI3jaFW6BUbFUX3M1zdTY2VihbFT9Kql-nF8FUiYlhlT2sSuSLK4IFIluRgUTzSPsoYD30-0lpvsH6axRGRmW5yyGdCd1kWB4iEAT7VwcycyTvM5ZrhLGzHFqqvxvtHeSMHgTp3Hs5AbKn48u6JIcgtshgbTg", "expires": 1851536632.2879884}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn\u0026vx_token=2\u0026staging_in_tao=0", "job": "AQAXBK_Qxs_xOUFlAUWzBbP8kydv4xKAIqIs-mudfTMzphHuO8TFGWY3DhverNo-YYVzk6zwOJ1Z5HJAarXAw6nACjYsNFA7AjJHNsInl9PDjd1vRyVdqWezFfW8VRaKKns_A-tas71oYAQH8TcD4YbNOQfi1tD0PVZqa5r5mKMd3Egbc-sMNOsa2qhhGghN7X4hE9U2C-umufyY4EyH7zvwHQF9atV6ZS_61swBgqWNMKxXxbp1ZawdE5w0XLeLbQOj3cwrOqZtX5MDh2P0wWVqXqDzac2e0esolopJQ37lMFn64Cg4iwbYksQwSgzm8oqKs8dvIUmdUfgyOoeUxepRFZ_HufqFTNm3WrKVGzEEEw", "expires": 1851536632.2881846}], "upload_id": "1536176631309", "xsharing_nonces": {}, "status": "ok"}
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn&vx_token=2&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 0-401042/1604175
DEBUG:instagram_private_api.client:RESPONSE: 201 0-401042/1604175
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn&vx_token=2&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 401043-802085/1604175
DEBUG:instagram_private_api.client:RESPONSE: 201 0-802085/1604175
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn&vx_token=2&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 802086-1203128/1604175
DEBUG:instagram_private_api.client:RESPONSE: 201 0-1203128/1604175
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=tsp_prn&vx_token=2&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 1203129-1604174/1604175
DEBUG:instagram_private_api.client:RESPONSE: 200 {"result": "deprecated", "configure_delay_ms": "6500", "status": "ok"}
ERROR:instagram_private_api.client:Received unexpected chunk upload response: {"result": "deprecated", "configure_delay_ms": "6500", "status": "ok"}
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    main(args)
  File "main.py", line 140, in main
    post_video(api, path, thumb_data, caption)
  File "/Users/guillaume/Documents/02-Projects/201803-Instamona/Git/Instamona/instagram/utils.py", line 102, in post_video
    api.post_video_story(data, size, duration, thumb)
  File "/Users/guillaume/miniconda3/envs/tf/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py", line 701, in post_video_story
    thumbnail_data=thumbnail_data, to_reel=True)
  File "/Users/guillaume/miniconda3/envs/tf/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py", line 622, in post_video
    code=500)
instagram_private_api.errors.ClientError: Upload has failed due to unexpected upload response: {"result": "deprecated", "configure_delay_ms": "6500", "status": "ok"}
```

**Comment by gu-ma** [comment]
It seems to be a problem with the encoding of the last frame or something like that? I've also updated moviepy but it does not seem to help...

**Comment by whicher** [comment]
Have you found a solution?

This is happening to me too. I have uploaded a couple of videos and then none of the accounts I have accepts any video.
I tried with many different formatted mp4 files no help. Even the ones I download from instagram itself.

Moviepy doesn't work on Ubuntu on Windows. So this makes things harder :/

**Comment by whicher** [comment]
Just found the root cause res.info's content type is "application/json; charset=utf-8" rather than "application/json" so upload.py can not interpret the last chunk as last chunk instead it treats as one of the intermediate ones. So fails with unexpected response.
Probably api response changed.

**Comment by ping** [comment]
Please test if the master branch fixes this for you.
