### ISSUE TITLE
i got error for login after some times

### ISSUE THREAD

**Issue by Painkiller1991** [ping/instagram_private_api#116]
i got an error like:
`Traceback (most recent call last):
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_private_api\client.py", line 506, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\MyTest.py", line 10, in <module>
    api = Client(user_name, password)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_private_api\client.py", line 197, in __init__
    self.login()
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 50, in login
    'accounts/login/', params=login_params, return_response=True)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_private_api\client.py", line 510, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Users\Saeed\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_private_api\errors.py", line 125, in process
    error_response=json.dumps(error_obj)
instagram_private_api.errors.ClientCheckpointRequiredError: checkpoint_challenge_required`

and when i use to go pnline with my browser, check my identity with sending security code, how to solve it that do not check my identity every time?

**Comment by ping** [comment]
@Painkiller1991

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
