### ISSUE TITLE
 Error 404: Not Found when variable name is used in feed_tag(tag)

### ISSUE THREAD

**Issue by zykloner** [ping/instagram_private_api#172]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Code to replicate the error must be provided below.

---

Paste the output of ``python -3.6` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client
def hastag_like()
    **tagss**="hashtag"
    rank_token = Client.generate_uuid()
    tag_results = []
    results = api.feed_tag(tagss, rank_token, exclude_list=[t['media_id'] for t in tag_results])
    posts = results.get('items', [])
    returtn posts;

Error/Debug Log:

```python
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "...instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../main.py", line 141, in <module>
    hastag_like(aa) #like and follows
  File ".../main.py", line 51, in hastag_like
    results = api.feed_tag(tagger, rank_token, exclude_list=[t['media_id'] for t in tag_results])
  File ".../instagram_private_api/endpoints/feed.py", line 172, in feed_tag
    res = self._call_api(endpoint, query=query_params)
  File ".../instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File ".../instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

```

The program gives no error when 

```python
# Example code that will produce the error reported
from instagram_web_api import Client
def hastag_like()
    #tagss="hashtag" when direct string is put into function instead of variable name
    rank_token = Client.generate_uuid()
    tag_results = []
    results = api.feed_tag("hastag", rank_token, exclude_list=[t['media_id'] for t in tag_results])
    posts = results.get('items', [])
    returtn posts;

**Comment by zykloner** [comment]
Issue got resolved. I was reading the string from file, but now i'm reading it from a large string in parts instead.
