### ISSUE TITLE
Getting "_io.BufferedReader has no len()" when trying to upload photo to story

### ISSUE THREAD

**Issue by THConer** [ping/instagram_private_api#213]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the lastest version v1.6.0
- [X] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [X] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [X] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

I've made a simple script that goes through a video and gets a thumbnail out of it. The script should then take this thumbnail and post it as a story to instagram.  

I am able to get the thumbnail just fine and save it. However, when I try to upload the Thumbnail as a story I get the following error:
`TypeError: object of type '_io.BufferedReader' has no len()`

At the beginning I thought that using a .png format might be causing an issue, so I switched the thumbnail to be a .jpg and I still got the same error

---

Paste the output of ``python -V`` here: Python 3.7.3 

Code:

```python
import TT
from moviepy.editor import *

api = TT.api

Video = open('./Videos/1.mp4', 'rb')
Clip = VideoFileClip('./Videos/1.mp4')
Duration = Clip.duration
Size=Clip.size

Clip.save_frame('./Videos/TNS.png', t=0)
Thumbnail = open('./Videos/TNS.png', 'rb')

api.post_photo_story(photo_data=Thumbnail, size=Size)

Video.close()
Thumbnail.close()
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "pg.py", line 14, in <module>                                                nts\upload.py", line 687, in post_photo_story
    api.post_photo_story(photo_data=Thumbnail, size=Size)
  File "C:\Users\MyUser\Desktop\NewTest\lib\site-packages\instagram_private_api\endpoi          .py", line 437, in post_photonts\upload.py", line 687, in post_photo_story                                       nts\upload
    photo_data=photo_data, size=size, to_reel=True)                                           6, in encode
  File "C:\Users\MyUser\Desktop\NewTest\lib\site-packages\instagram_private_api\endpoints\upload.py", line 437, in post_photo                                             y", line 80, in iter
    content_type, body = MultipartFormDataEncoder().encode(fields, files)
  File "C:\Users\MyUser\Desktop\NewTest\lib\site-packages\instagram_private_api\http.py", line 86, in encode                                                              y", line 8
    for chunk, _ in self.iter(fields, files):
  File "C:\Users\MyUser\Desktop\NewTest\lib\site-packages\instagram_private_api\http.py", line 80, in iter
    yield (fd, len(fd))
TypeError: object of type '_io.BufferedReader' has no len()
```

Would appreciate any help I can get with this issue

**Comment by THConer** [comment]
Apologies, completely forgot to read the content of the files I just opened. This is my new code:

```python
import TT
from moviepy.editor import *

api = TT.api

Video = open('./Videos/1.mp4', 'rb')
Clip = VideoFileClip('./Videos/1.mp4')
Duration = Clip.duration
Size=Clip.size

Clip.save_frame('./Videos/TNS.jpg', t=0)
Thumbnail = open('./Videos/TNS.jpg', 'rb')

api.post_photo_story(photo_data=Thumbnail.read(), size=Size)

Video.close()
Thumbnail.close()
```
