### ISSUE TITLE
Logging in requires OTP

### ISSUE THREAD

**Issue by sharunkumar** [ping/instagram_private_api#240]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

>Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I tried using this api but I am not able to log in (error log attached) plus I am getting an OTP on my mobile number registered with instagram.

>Code to replicate the error must be provided below.

```python
from instagram_private_api import Client, ClientCompatPatch

user_name = '[redacted]'
password = '[redacted]'

api = Client(user_name, password)
```

---

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

web_api = Client()
user_feed_info = web_api.user_feed('1234567890', count=10)
```

Error/Debug Log:

```python
> Executing task: python app\main.py <

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\instagram_private_api\client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "C:\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\main.py", line 6, in <module>
    api = Client(user_name, password)
  File "C:\Python37\lib\site-packages\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "C:\Python37\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 50, in login
    'accounts/login/', params=login_params, return_response=True)
  File "C:\Python37\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Python37\lib\site-packages\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Bad Request
The terminal process terminated with exit code: 1
```

**Comment by Mishul-G** [comment]
Hey @sharunkumar were you able to get this working? Is this thread dead?

**Comment by sharunkumar** [comment]
@Mishul-G hope haven't found a way to make this work. I guess this is because I have TFA enabled on my account 🤔 maybe turning it off would make it work

**Comment by Mishul-G** [comment]
Yeah that’s worth a try. Are any other aspects of api working that you have tried?

**Comment by sharunkumar** [comment]
I just played around with the api many months ago and it seemed to be working fine. but this TFA problem is new to me

**Comment by autoiue** [comment]
There is a fork that provides 2FA methods here : https://github.com/pbotsman/instagram_private_api
