### ISSUE TITLE
it is not working when use post_photo

### ISSUE THREAD

**Issue by bobbybubble** [ping/instagram_private_api#242]
it is not working when use post_photo, also post_album, please fix it, many tks

**Comment by toughyear** [comment]
I am also facing this issue.
Here is a link to where I faced this error
https://ibb.co/PxyXNM6

**Comment by Limfocit** [comment]
same for me. I get the same log provided in the previous comment. Please kindly help!

**Comment by vladartym** [comment]
Same, I'm having trouble posting an image.

**Comment by dexredux** [comment]
same issue.

**Comment by pravintandale007** [comment]
same issue.

**Comment by JulianToledano** [comment]
Looks like instagram close that endpoint :astonished:. 
Only [Instagram business can use it](https://developers.facebook.com/docs/instagram-api/guides/content-publishing/)

**Comment by shelsoloa** [comment]
Any updates on this? I've encountering the same error.

Here it is in it's entirety:

```

/.../venv/lib/python3.8/site-packages/instagram_private_api/endpoints/upload.py:397: UserWarning: This endpoint has not been fully tested.
  warnings.warn('This endpoint has not been fully tested.', UserWarning)
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/.../venv/lib/python3.8/site-packages/instagram_private_api/endpoints/upload.py", line 446, in post_photo
    response = self.opener.open(req, timeout=self.timeout)
  File "/.../.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/.../.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/.../.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/.../.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/.../.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instatest.py", line 117, in <module>
    post_photo(api)
  File "instatest.py", line 61, in post_photo
    api.post_photo(img_data, img_size, caption='This is a test')
  File "/.../venv/lib/python3.8/site-packages/instagram_private_api/endpoints/upload.py", line 450, in post_photo
    ErrorHandler.process(e, error_response)
  File "/.../venv/lib/python3.8/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Bad Request

```

I've also tried using the [extensions](https://github.com/ping/instagram_private_api_extensions) module but to no avail.

@JulianToledano I don't believe it's related to the ContentPublishing pipeline. That has always been blocked off, thus, unless this never worked it would have to be something else?

**Comment by JulianToledano** [comment]
@shelsoloa I don't know if it is related to the ContentPublishing pipeline or not. What i know is that there was and endpoint before that let you do it. Somehow the reality is that now you just can upload pics with web scrapping. :anguished:

**Comment by shelsoloa** [comment]
> @shelsoloa I don't know if it is related to the ContentPublishing pipeline or not. What i know is that there was and endpoint before that let you do it. Somehow the reality is that now you just __can upload pics with web scrapping__. anguished

Wait.. can or cant?

If there's a way to do this I would love a lead on it.

**Comment by dreygur** [comment]
Same problem! 🥺
