### ISSUE TITLE
instagram_private_api Not working and show HTTP Error 500

### ISSUE THREAD

**Issue by 11348** [ping/instagram_private_api#290]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

instagram_private_api not working right now and show ERROR 500 when using

Code:

```python
# Example code that will produce the error reported
from instagram_private_api import Client

api = Client(igac, igpw)
```

Error/Debug Log:

```python
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 49, in login
    login_response = self._call_api(
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Users\good\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\errors.py", line 141, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Internal Server Error
```

**Comment by j-holub** [comment]
same

**Comment by 11348** [comment]
resume normal

**Comment by prafulbagai** [comment]
A similar kind of error arises in `instagram_web_api`. 

```
from instagram_web_api import Client
web_api = Client(auto_patch=True, drop_incompat_keys=False)
```

@11348 any comments on this?
