### ISSUE TITLE
Can't tag other users than my followers

### ISSUE THREAD

**Issue by target111** [ping/instagram_private_api#299]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Can't post a comment that tags a person that doesn't follow me.

---

Paste the output of ``python -V`` here: Python 3.8.5

Code:

```
api.post_comment(media_id, f'@{follower}')
        print(f'Tagged: {follower}')
```

Error/Debug Log:

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)                         File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)                                                 File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:              
Traceback (most recent call last):
  File "instaway.py", line 57, in <module>
    main()
  File "instaway.py", line 53, in main
    run(parse_args())
  File "instaway.py", line 45, in run
    api.post_comment(media_id, f'@{follower}')
  File "/data/data/com.termux/files/home/projects/instaway/lib/client.py", line 14, in post_comment
    self.api.post_comment(media_id, comment)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instagram_private_api/endpoints/media.py", line 266, in post_comment
    res = self._call_api(endpoint, params=params)                                  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instagram_private_api/client.py", line 527, in _call_api                                          ErrorHandler.process(e, error_response)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)                instagram_private_api.errors.ClientError: Bad Request: failed to mention
```

**Comment by target111** [comment]
I found out the issue, some users don't allow tags from users they don't follow. Closing this.
