### ISSUE TITLE
api.post_like() results in a runtime error

### ISSUE THREAD

**Issue by oriyonay** [ping/instagram_private_api#301]
## Describe the Bug/Error:
when I try to like a photo (after successfully logging in) gives a runtime error
The terminal outputs: "WARNING:instagram_private_api.errors:Error parsing error response: Expecting value: line 1 column 1 (char 0)". I just updated to the latest version of the API and the error persists. I am using the instagram_private_api client.

---

Paste the output of ``python -V`` here:
Python 3.7.7

Code:

```python
# After logging in using the example script savesettings_logincallback.py:
UUID = api.generate_uuid()
api.post_like(2400935294076438784_30464350)
```

Error/Debug Log:

```python
Client version: 1.6.0
Reusing settings: test.txt
Cookie Expiry: 2020-12-18T15:19:32Z
Setup ok
WARNING:instagram_private_api.errors:Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tennex.py", line 152, in <module>
    api.post_like(2400935294076438784_30464350)
  File "/usr/local/lib/python3.7/site-packages/instagram_private_api/endpoints/media.py", line 360, in post_like
    res = self._call_api(endpoint, params=params, query={'d': '1'})
  File "/usr/local/lib/python3.7/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/usr/local/lib/python3.7/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Internal Server Error
```

**Comment by aechaechaech** [comment]
This is incredibly late but i'm pretty sure you have to pass in media_id as a string. 

Doing something like `api.post_like("2538017036670722162_528817151")` works fine for me.

**Comment by oriyonay** [comment]
oh my goodness haha, i really don't know how i didn't catch that!!! thank you so much!
