### ISSUE TITLE
Getting error in private api, instagram updates there api 

### ISSUE THREAD

**Issue by gaur-avvv** [ping/instagram_private_api#412]
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Osintgram/main.py", line 125, in <module>
    api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/src/Osintgram.py", line 47, in __init__
    self.setTarget(target, True)
  File "/home/kali/Osintgram/src/Osintgram.py", line 61, in setTarget
    self.following = self.check_following()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/src/Osintgram.py", line 176, in check_following
    return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/errors.py", line 141, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

Getting error I think you need to update your code and if possible give me you old code if I can Do something!

**Comment by rafaelfaria** [comment]
+1

**Comment by AlizerUncaged** [comment]
this project looks like its not being maintained anymore, I recommend using https://github.com/adw0rd/instagrapi instead

**Comment by root07LINUX** [comment]
rror parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Osintgram/main.py", line 121, in <module>
    api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/src/Osintgram.py", line 47, in __init__
    self.setTarget(target)
  File "/home/kali/Osintgram/src/Osintgram.py", line 60, in setTarget
    self.following = self.check_following()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/src/Osintgram.py", line 1160, in check_following
    return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/home/kali/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found
 helpppppppp
