### ISSUE TITLE
ClientError: Forbidden when I send videos to stories. And everything works with photos.

### ISSUE THREAD

**Issue by nxexox** [ping/instagram_private_api#71]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.5
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

Python Version ``2.7.13``

Code:

```python
from __future__ import unicode_literals
from instagram_private_api import (  
    Client, ClientError, ClientLoginError,  
    ClientCookieExpiredError, ClientLoginRequiredError,  
    MediaRatios  
)


video = 'test_instagram.mp4'
thumb = 'test_instagram.jpg'

client = Client('username', 'password')

with open(video, 'rb') as video_f, open(thumb, 'rb') as thumb_f:
	# Exception on client.post_video_story called.
    result = client.post_video_story(
        video_f,
        video.pixels_size,
        video.get_duration(),
        thumb_f.read()
    )
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/endpoints/upload.py", line 701, in post_video_story
    thumbnail_data=thumbnail_data, to_reel=True)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/endpoints/upload.py", line 661, in post_video
    upload_id, size, duration, thumbnail_data)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/endpoints/upload.py", line 342, in configure_video_to_reel
    res = self.post_photo(thumbnail_data, size, '', upload_id=upload_id, to_reel=True)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/endpoints/upload.py", line 473, in post_photo
    return self.configure_to_reel(upload_id, size)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/endpoints/upload.py", line 323, in configure_to_reel
    res = self._call_api(endpoint, params=params)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/client.py", line 492, in _call_api
    ErrorHandler.process(e, error_response)
  File "/python2/local/lib/python2.7/site-packages/instagram_private_api/errors.py", line 137, in process
    raise ClientError(error_msg, http_error.code, error_response)
ClientError: Forbidden
```

### Describe your issue

When I try to upload videos to stories, this error occurs. When I try to upload a photo to stories through ``post_photo_story`` then the upload works completely.
Video and image features:
Video: ``613x818 pixels`` ``video/mp4 mime-type`` ``961846 bytes`` ``8 sec duration``
Image: ``612x818 pixels``  ``image/jpg mime-type`` ``32771 bytes``

**Comment by ping** [comment]
Thanks for the report. Looks like something's changed and the ``post_video_story()`` doesn't work anymore. Video posting is a major pain to troubleshoot so don't expect any fixes soon.

**Comment by nxexox** [comment]
Thank you for the answer. Then you can announce the estimated time of repair? Let it a week, a month, or two months for example.

**Comment by ping** [comment]
There is no ETA.

**Comment by b3nab** [comment]
Hi @ping ,
you are doing a great job with this library, really helpful.
For this issue, do you have some suggestion on how to inspect the code to find this bug? Where to start looking around? Or at least where it's located to run some debugging?

**Comment by Sovetnikov** [comment]
@nxexox Is there any success with this error?

**Comment by Sovetnikov** [comment]
Seems 'for_album' parameter fixes this issue in post_video() call to 'upload/video/' endpoint:
`        if to_reel:
            params['for_album'] = '1'`

**Comment by eduardoegos** [comment]
@Sovetnikov solution works for me
