### ISSUE TITLE
Video uploads failing

### ISSUE THREAD

**Issue by BitJunky** [ping/instagram_private_api#9]
###  Have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``) + (```instagram_private_api_extensions```)
- [ ] web (``instagram_web_api/``)

### Purpose of issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Output of ``python -V`` :
Python 2.7.10

### Example code that will produce the error reported :

```
import json
import codecs
import datetime
import os.path
import logging
import argparse
import traceback

try:
    import instagram_private_api as app_api
except ImportError:
    import sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    import instagram_private_api as app_api

from instagram_private_api_extensions import media

def to_json(python_object):
    if isinstance(python_object, bytes):
        return {'__class__': 'bytes',
                '__value__': codecs.encode(python_object, 'base64').decode()}
    raise TypeError(repr(python_object) + ' is not JSON serializable')


def from_json(json_object):
    if '__class__' in json_object:
        if json_object['__class__'] == 'bytes':
            return codecs.decode(json_object['__value__'].encode(), 'base64')
    return json_object


def onlogin_callback(api, new_settings_file):
    cache_settings = api.settings
    with open(new_settings_file, 'w') as outfile:
        json.dump(cache_settings, outfile, default=to_json)
        print('SAVED: %s' % new_settings_file)


if __name__ == '__main__':

    logging.basicConfig()
    logger = logging.getLogger('instagram_private_api')
    logger.setLevel(logging.WARNING)

    # Example command:
    # python examples/savesettings_logincallback.py -u "yyy" -p "zzz" -settings "test_credentials.json"
    parser = argparse.ArgumentParser(description='login callback and save settings demo')
    parser.add_argument('-settings', '--settings', dest='settings_file_path', type=str, required=True)
    parser.add_argument('-u', '--username', dest='username', type=str, required=True)
    parser.add_argument('-p', '--password', dest='password', type=str, required=True)
    parser.add_argument('-debug', '--debug', action='store_true')

    args = parser.parse_args()
    if args.debug:
        logger.setLevel(logging.DEBUG)

    print('Client version: %s' % app_api.__version__)

    try:

        settings_file = args.settings_file_path
        if not os.path.isfile(settings_file):
            # settings file does not exist
            print('Unable to find file: %s' % settings_file)

            # login new
            api = app_api.Client(
                args.username, args.password,
                on_login=lambda x: onlogin_callback(x, args.settings_file_path))
        else:
            with open(settings_file) as file_data:
                cached_settings = json.load(file_data, object_hook=from_json)
            print('Reusing settings: %s' % settings_file)

            # reuse auth settings
            api = app_api.Client(
                args.username, args.password,
                settings=cached_settings)

    except (app_api.ClientCookieExpiredError, app_api.ClientLoginRequiredError) as e:
        print('ClientCookieExpiredError/ClientLoginRequiredError: %s' % e)

        # Login expired
        # Do relogin but use default ua, keys and such
        api = app_api.Client(
            args.username, args.password,
            on_login=lambda x: onlogin_callback(x, args.settings_file_path))

    except app_api.ClientLoginError as e:
        print('ClientLoginError %s' % e)
        exit(9)
    except app_api.ClientError as e:
        print('ClientError %s (Code: %d, Response: %s)' % (e.msg, e.code, e.error_response))
        exit(9)
    except Exception as e:
        print('Unexpected Exception: %s' % e)
        exit(99)

    # Show when login expires
    cookie_expiry = api.cookie_jar.expires_earliest
    print('Cookie Expiry: %s' % datetime.datetime.fromtimestamp(cookie_expiry).strftime('%Y-%m-%dT%H:%M:%SZ'))

    # Call the api
    results = api.tag_search('cats')
    assert len(results.get('results', [])) > 0
    print('All ok')
	
    try :
        # post a video story
        vid_data, vid_size, vid_duration, vid_thumbnail = media.prepare_video('8.mp4', aspect_ratios=api.reel_ratios())
        api.post_video_story(vid_data, vid_size, vid_duration, vid_thumbnail)
    except :
        var = traceback.format_exc()
        with open('log.txt', 'w') as log:
            log.write(var)
```

### Error/Debug Log :
```
Traceback (most recent call last):
  File "myUpload.py", line 116, in <module>
    api.post_video_story(vid_data, vid_size, vid_duration, vid_thumbnail)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py", line 592, in post_video_story
    thumbnail_data=thumbnail_data, to_reel=True)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py", line 567, in post_video
    return self.configure_video_to_reel(upload_id, size, duration, thumbnail_data)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py", line 298, in configure_video_to_reel
    res = self.post_photo(thumbnail_data, size, '', upload_id=upload_id, to_reel=True)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py", line 431, in post_photo
    return self.configure_to_reel(upload_id, size)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py", line 279, in configure_to_reel
    res = self._call_api(endpoint, params=params)
  File "D:\insta\ping\instagram_private_api\instagram_private_api\client.py", line 434, in _call_api
    raise ClientError(error_msg, e.code, error_response)
ClientError: Bad Request: Transcode error: Video file does not contain duration
```

### Issue

When above code ran with,
```python myUpload.py -u "username" -p "password" -settings "user.json"```
Video uploads fails , with ```Transcode error: Video file does not contain duration ```

**Comment by ping** [comment]
Please don't post screenshots. It's unreadable. Post text only.
Also, the full code to reproduce this error.

**Comment by BitJunky** [comment]
Updated issue description with relevant information.

**Comment by ping** [comment]
I cannot reproduce the error with the exact same code you've provided.

Try running with ``-debug``
``python myUpload.py -u "username" -p "password" -settings "user.json" -debug`` 

Post the full debug log here.

**Comment by BitJunky** [comment]
```
DEBUG:instagram_private_api.client:REQUEST: https://i.instagram.com/api/v1/upload/video/ POST
DEBUG:instagram_private_api.client:DATA: upload_media_height=816&upload_id=149075802xxxx&upload_media_width=612&upload_media_duration_ms=14760&media_type=2&_uuid=e07f7bee-xxxx-xxxx-9887-1c7508ccxxxx&_csrftoken=2jwN9WIy3RGUDchqHo9o7XbVSQxxxxxx
DEBUG:instagram_private_api.client:RESPONSE: 200 {"status": "ok", "upload_id": "149075802xxxx", "video_upload_urls": [{"job": "AQA_1z3mhcG7grCcJKe9WCW-z7hO_gdSM4MiN8x2Z8YWL0AvhHfBCrKxk9JTg7XZwRYclrmhyZKhw_5ryEXpW5CjMRff0ErlZXCJul6uYGnq7CI3KMzbJ6afcOz6TED2YC5riFKeB0EjxdPkflzwkClBQFR-C5PTxKkZ2jpvdjFjOpdw6vzRCwcb8lxNmP3YaiukVsFyDR49rLHxSvIKeVkw6EE5aDK7IeG4_Xva_eXOlvT62aTRPu8LnEizT5oFuKUPqdHjdwJpzN9Wl4-xuLIZQtACS6aUFf7ySwoGNEhoaYjYEieplm_yzZUMTwsmg7XJgN_l6kZzHYeLlptO43MQgXhDumok7vYVeYI1xxxxxx", "expires": 1806118028.8593752, "url": "https://upload.instagram.com/api/v1/stage/video/?target=frc3c11\u00xxxx_token=1xxxx\u0026staging_in_tao=0"}, {"job": "AQCwlT7iATgYEoP2tiMucONhs7IuUsx5N09rChHuAEXFVU94ili3lKuuAbi6aZEwQnp0v2hA5s6JBrAMjePM2UkdgvcU25dgf2VRucBFE-UIfyeBz5zo2Vsaxkqtfj-_NEiCOi_tvyV1u09S3JWkML63ZCVzPeu-5gQJTMt8sd0HGSTND6v_Kz3u_n_ZqeWO8Y3jmeqyDQQgl7gQkAAsx5BRisDkrDDYTIs4W2jh0t4IvZRAoqextmbveUiHFFZIwkCWQavSI_thyNbJTGoXXsf7tfhMbIYP4Q6Gjn2HIGkrNYgn2Cs7EjTz105w6Xn3XVECklrMQ30yvbsSTX7-zNiQuOILIF4tbqp7nOs_xxxxxx", "expires": 1806118028.8601, "url": "https://upload.instagram.com/api/v1/stage/video/?target=frcxxxx\u00xxxx_token=1xxxxx\u0026staging_in_tao=0"}, {"job": "AQAhZEvj5PyKFv7_8ZRpWdCKLRnHO0udAhwaYHTNG-VDzhXzY1Z4of7yeG8knG2TbYCFUGqXrorDHkfYv5lXu6Z7a65x7VkiY1TZbYCqCkFKikiudVaaF72AOYUOtBlemAiGXkltp2rY75zPZp4ZQ5CmLIuSqonSwVBIYMZpVIwmmtp-oRRhmK1_a6ATdNJlapVWJH8RFZamyAUNd2QCGqq4Q6Vba9hZF1LkZeD6vyTCIyNnC34szXAcaNh5t5z2LFdEDbflXHcqwZtGpYIkcSHZHlmd1PE9f-E1pr28j2SCCinOPn3-5uUyv20fsq378KNEFFqbpNGGSBsT8FRDI8aph_hfkwU43M4X1I82xxxxxx", "expires": 1806118028.8608296, "url": "https://upload.instagram.com/api/v1/stage/video/?target=frcxxxx\u00xxxx_token=1xxxx\u0026staging_in_tao=0"}, {"job": "AQCWSjYPrn6rrmatlVYijyusYmxSGHKipY9RiD2itgsYUkVZ7r_KZppGXAylp9JWKuT3IiDvmUcnXKMTDR3GSANlMd7L1yAOog-hftoHdBlNwTg9NA7IQ-8lUb5HSwFDlDB6QsKJ4NcivYn47bBLpuXKFXKjF5V_RjbcW19urH_knUtko7IJxeRat5fhzUgu_eHory42RIJUbKn-yXoneQ-IDHAj1nmOAAXW-qu1QdMUpS3lhTRy-9l2_GrI-Q7dIKIQPjbwQn8LrL1guiggYHbJlV2ysoT5Q5C0-8WuNdM71bybrYF2RoZNczm6PGtcpskFzt5GtmWMFaxW6jj_ZFRct6mngISxNsKtZgknxxxxxx", "expires": 1806118028.8615792, "url": "https://upload.instagram.com/api/v1/stage/video/?target=frcxxx\u00xxxx_token=1xxxx\u0026staging_in_tao=0"}]}
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=frcxxx&vx_token=1xxxx&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 0-478/1918
DEBUG:instagram_private_api.client:RESPONSE: 201 0-478/1918
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=frcxxxx&vx_token=1xxxx&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 479-957/1918
DEBUG:instagram_private_api.client:RESPONSE: 201 0-957/1918
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=frcxxxx&vx_token=1xxxx&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 958-1436/1918
DEBUG:instagram_private_api.client:RESPONSE: 201 0-1436/1918
DEBUG:instagram_private_api.client:POST https://upload.instagram.com/api/v1/stage/video/?target=frcxxxx&vx_token=1xxxx&staging_in_tao=0
DEBUG:instagram_private_api.client:Uploading Content-Range: bytes 1437-1917/1918
DEBUG:instagram_private_api.client:RESPONSE: 200 {"status": "ok", "configure_delay_ms": "6500", "result": "deprecated"}
DEBUG:instagram_private_api.client:Configure delay: 6.5
WARNING:py.warnings:D:\insta\ping\instagram_private_api\instagram_private_api\endpoints\upload.py:353: UserWarning: This endpoint has not been fully tested.
  warnings.warn('This endpoint has not been fully tested.', UserWarning)

DEBUG:instagram_private_api.client:POST https://i.instagram.com/api/v1/upload/photo/
DEBUG:instagram_private_api.client:RESPONSE: 200 {"status": "ok", "upload_id": "149075802xxxx"}
DEBUG:instagram_private_api.client:REQUEST: https://i.instagram.com/api/v1/media/configure_to_story/ POST
DEBUG:instagram_private_api.client:DATA: ig_sig_key_version=4&signed_body=7d85662f3f0857325e166fe8924f6331dc09907675676382bcfa318dc7a6eec0.%7B%22extra%22%3A%7B%22source_width%22%3A612%2C%22source_height%22%3A816%7D%2C%22_uuid%22%3A%22e07f7bee-xxxx-xxxx-9887-1c7508cc9d7e%22%2C%22client_shared_at%22%3A%221490758052%22%2C%22device%22%3A%7B%22android_release%22%3A%224.3%22%2C%22model%22%3A%22HM+1SW%22%2C%22android_version%22%3A18%2C%22manufacturer%22%3A%22Xiaomi%22%7D%2C%22_csrftoken%22%3A%222jwN9WIy3RGUDchqHo9o7XbVSQMzZn4m%22%2C%22client_timestamp%22%3A%221490758056%22%2C%22source_type%22%3A%224%22%2C%22edits%22%3A%7B%22crop_center%22%3A%5B0.0%2C0.0%5D%2C%22crop_zoom%22%3A1.3333334%2C%22crop_original_size%22%3A%5B612.0%2C816.0%5D%7D%2C%22_uid%22%3A%224737188995%22%2C%22upload_id%22%3A%221490758026081%22%2C%22story_media_creation_date%22%3A%221490758037%22%2C%22configure_mode%22%3A1%7D
DEBUG:instagram_private_api.client:RESPONSE: 400 {"status": "fail", "message": "Transcode error: Video file does not contain duration"}
```

**Comment by ping** [comment]
Can't see what's wrong except that your video size appears to be extraordinarily small at 1.9k bytes for a 14+second 612x816 video. Have you tried with another video?

You can also try to save the modified video
```python
media.prepare_video('8.mp4', aspect_ratios=api.reel_ratios(), save_path='8_modified.mp4')
```
And check the saved file to see if it's playable/corrupt.

**Comment by BitJunky** [comment]
Modifed file works fine.

**Comment by ping** [comment]
I don't have any suggestions other than it's possibly due to something different about your video file. Have you tried with another video?

You can also try posting the video story using the official app with this particular video file and see if it works.

**Comment by ping** [comment]
@BitJunky I cannot reproduce the error at all. Like i asked before, have you tried posting the story via the official app with the same video and account?

It may also be helpful if you provide the failing video.

**Comment by ping** [comment]
Closed due to inactivity.
